DROP DATABASE IF EXISTS onetomanybidirectionalmixjava2novice;
CREATE DATABASE IF NOT EXISTS onetomanybidirectionalmixjava2novice CHARACTER SET utf8 COLLATE utf8_general_ci;
USE onetomanybidirectionalmixjava2novice;
DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(

                      ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
                      STREET_NAME VARCHAR(50),
                      CITY_NAME VARCHAR(50),
                      STATE_NAME VARCHAR(255),
                      PIN_CODE INTEGER,
                      PRIMARY KEY (ADDRESS_ID)
)
  ENGINE = innoDB
  DEFAULT CHARACTER SET = utf8
;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE(
                       EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
                       ADDRESS_ID INTEGER,
                       EMPLOYEE_NAME VARCHAR(200) NOT NULL,
                       EMAIL VARCHAR(255),
                       DATE_OF_JOIN TIMESTAMP,
                       SALARY DOUBLE PRECISION,
                       PRIMARY KEY (EMPLOYEE_ID),
                       FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
)
  ENGINE = innoDB
  DEFAULT CHARACTER SET = utf8
;
INSERT INTO ADDRESS(ADDRESS_ID, STREET_NAME, CITY_NAME, STATE_NAME, PIN_CODE) VALUES (1, 'Danyla Halytskogo str.','Ternopil', 'Ukraine', 46010);
INSERT INTO ADDRESS(ADDRESS_ID, STREET_NAME, CITY_NAME, STATE_NAME, PIN_CODE) VALUES (2, 'Petra Halytskogo str.','Berezhany', 'Ukraine', 46011);
INSERT INTO ADDRESS(ADDRESS_ID, STREET_NAME, CITY_NAME, STATE_NAME, PIN_CODE) VALUES (3, 'Vasyla Halytskogo str.','Kozova', 'Ukraine', 46012);
INSERT INTO ADDRESS(ADDRESS_ID, STREET_NAME, CITY_NAME, STATE_NAME, PIN_CODE) VALUES (4, 'Romana Halytskogo str.','Terebovlya', 'Ukraine', 46013);

INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (1, 'Peter Petrenko', '123@gmail.com', CURRENT_TIMESTAMP, 5000);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (1, 'Vasyl Petrenko', '124@gmail.com', CURRENT_TIMESTAMP, 6000);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (1, 'Stas Petrenko', '1254@gmail.com', CURRENT_TIMESTAMP, 5050);

INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (2, 'Stas Stasyuk Petrenko', '127@gmail.com', CURRENT_TIMESTAMP, 6044);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (2, 'Vlad Romanenko', '1274@gmail.com', CURRENT_TIMESTAMP, 6046);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (2, 'Vlad Nechyporuk', '17896@gmail.com', CURRENT_TIMESTAMP, 6054);

INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (3, 'Ostap Ostapchenko', '14567@gmail.com', CURRENT_TIMESTAMP, 6044);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (3, 'Roman Romanenko', '1123274@gmail.com', CURRENT_TIMESTAMP, 6046);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (3, 'Sydir Nechyporuk', '11477896@gmail.com', CURRENT_TIMESTAMP, 6054);

INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (4, 'Ostap Ostapchenko Petrenko', '14567@gmail.com', CURRENT_TIMESTAMP, 6044);
INSERT INTO EMPLOYEE(ADDRESS_ID, EMPLOYEE_NAME, EMAIL, DATE_OF_JOIN, SALARY) VALUES (4, 'Roman Romanenko Nechyporuk', '1123274@gmail.com', CURRENT_TIMESTAMP, 6046);
